### ISSUE TITLE
Virtualgo does not work well with delve

### ISSUE THREAD

**Issue by Taik** [GetStream/vg#11] opened 2017-08-09 13:05 UTC
I'm currently using Gogland for go development. Switching over to vg definitely helps with reducing CPU load and in general making gogland snappier.

Running tests still works as expected. When setting breakpoints and running tests in debug mode, it seems like the breakpoints are not registering at all. My current fallback solution is to set GOPATH back to my default global path, effectively disabling `vg`, but that defeats the purpose of using it in the first place :)

This may be an OS X thing and how it deals with symlinks, but I thought I'd see if anyone else has a good way of dealing with this.

**Comment by tbarbugli** [comment] 2017-08-09 13:19
OSX and Gogland user here :) Can you provide more information on how I can try reproducing this?

**Comment by JelteF** [comment] 2017-08-09 13:28
There's definitely some issues with the symlink approach in full isolation mode. Have you tried using it in global fallback mode to see if that solves the issue: https://github.com/GetStream/vg#workspaces-with-global-gopath-fallback

Another solution I'm working on is by using [bindfs](http://bindfs.org/) mounts instead of symlinks, it can be found on the [bindfs branch](https://github.com/GetStream/vg/tree/bindfs). All commands that support specifying a full package path should work like normal with this branch. 

I've been using this branch for myself for a while now and haven't run into issues. If you could give it a spin and see if it fixes the delve issue you're having that would be really great. You would have to install `bindfs` though, on mac it should be `brew install bindfs`. You probably have to `destroy` the workspace and recreate it again by `activate` it.

If you try out the bindfs branch there's one IMPORTANT thing to keep in mind. Don't delete the workspace directory manually (`~/.virtualgo/<workspaceName>`), otherwise it will actually delete the files inside your local installs. You should only remove the workspace by using `vg destroy`, which first unmounts the `bindfs` mounts. Other than that it should only improve upon the symlink approach.

**Comment by Taik** [comment] 2017-08-09 14:51
@tbarbugli I'm currently using:
```
$ vg version
0.6.0
```

To reproduce, just set a breakpoint within any existing test case, and debug the test (`CTRL + Shift + D`). You should see that the breakpoint just gets skipped completely.

@JelteF I tried with global fallback and it doesn't seem to be breaking. I added both the virtualgo GOPATH and my global GOPATH as fallback. I'll give bindfs branch a try and report back!

**Comment by Taik** [comment] 2017-08-09 15:09
@JelteF this is unrelated, but `vg moveVendor` gets stuck for me:

```bash
$ vg moveVendor                                                                                                                                                                                                                                                                                                                                                         
Uninstalling "github.com/reservemedia/reservation-srv" from workspace
  Unmounting bindfs mount at "/Users/thinh/.virtualgo/reservation-srv/src/github.com/reservemedia/reservation-srv"
```

**Comment by JelteF** [comment] 2017-08-09 16:21
Good to hear setting global GOPATH works. But your bindfs thing is weird. I only had that happen when I was actually accessing it. Could you try unmounting it manually using `fusermount -u ~/.virtualgo/reservation-srv/src/github.com/reservemedia/reservation-srv`? Because that's what vg is trying to do.

**Comment by Taik** [comment] 2017-08-10 13:29
@JelteF Yep it's definitely weird; unmounting it manually works for me. Is there any hidden debug flags I can set in order to get some useful output for you?

**Comment by JelteF** [comment] 2017-08-10 13:48
You can see that it's calling `fusermount -u <dir>` there. But if that works when you do it manually I'm guessing that's not where it gets stuck I guess. Maybe it's something as stupid as this line:
```
io.Copy(outputBuff, os.Stderr) 
```

**Comment by Taik** [comment] 2017-08-10 13:56
@JelteF my apologies, I didn't expect it to execute the actual command, haha. I don't have fusermount on my system, so changing L171 to use `umount` worked for me.

```go
cmd := exec.Command("umount", pkgSrc)
```

**Comment by Taik** [comment] 2017-08-10 13:59
Just tested debugging, everything works with `bindfs`.

**Comment by JelteF** [comment] 2017-08-15 15:07
I just pushed a some changes to the bindfs branch that should make it work on OSX. @Taik could you see let me know if this is indeed the case?

**Comment by Taik** [comment] 2017-08-21 13:52
@JelteF it works for me!

**Comment by JelteF** [comment] 2017-08-22 09:30
Good to hear :). And no `vg deactivate` shouldn't unmount, because it could be that you have the same workspace activated twice. 

Also, I've changed the `bindfs` branch to default to global fallback mode again in preparation of the next release. I did this, because global fallback interferes the least with go tooling usage. If you still want to use full isolation, you should use the `--full-isolation` flag of `vg init` when initially creating a workspace. See the new section in the updated README for some more info: https://github.com/GetStream/vg/tree/bindfs#workspace-import-modes

**Comment by JelteF** [comment] 2017-09-04 11:28
Just released the changes from the `bindfs` branch: https://github.com/GetStream/vg/releases/tag/v0.7.0

So I'm closing this now

**Closed by JelteF** 2017-09-04 11:28 UTC
Labels: bug
